import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import { FontProvider } from "./context/FontContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <FontProvider>
        <ThemeProvider>
        {children}
        </ThemeProvider>
        </FontProvider>
      </body>
    </html>
  );
}
